exports.user_email = new RegExp('^[a-zA-Z0-9.-_]+[@]{1}[a-zA-Z0-9.-_]+[.]{1}[a-z]{2,4}$')
exports.user_password = new RegExp('^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$')
exports.user_login = new RegExp('^[^@&\"()<>!_$*€£`+=\\/;?#]+$')
exports.tokenRegex = new RegExp('^[\w]{6}$')
exports.game_name = new RegExp('^[^<>]+$')
exports.game_pic = new RegExp('^[^<>]+$')
exports.game_desc = new RegExp('^[^<>]+$')